### ISSUE TITLE
cannot find lgrid2grid

### ISSUE THREAD

**Issue by yaoyi92** [eth-cscs/COSMA#84] opened 2021-04-12 19:19 UTC
Dear developers, I am trying to link against COSMA via the [USE COSMA in 30 seconds](https://github.com/eth-cscs/COSMA#using-cosma-in-30-seconds). However, it tells me grid2grid is not found. I saw you updated grid2grid to COSTA. Should the linking libs also update? If yes, what's the correct lib to be linked? I saw libcosta.a, libcosta_prefixed_scalapack.a, and libcosta_scalapack.a.

Thank you so much.

**Comment by kabicm** [comment] 2021-04-12 20:04
Dear Yi, thanks for spotting this! You are totally right, grid2grid was changed to COSTA and this will be corrected in the README soon, we are preparing a new release in both COSTA and COSMA. 

In your case, you should like to `libcosta_scalapack.a`, because of this line: https://github.com/eth-cscs/COSMA/blob/35e2ddaeda9310e1bf27837240c93a9468575272/src/cosma/CMakeLists.txt#L54

Let me know if it works for you!

**Comment by kabicm** [comment] 2021-04-12 20:08
In general, if you use pure `cosma` library (without pxgemm wrappers) then you link to `costa`. If you use `cosma_pxgemm` then you link to `costa_scalapack`. Pay attention that `costa_scalapack` overwrites scalapack's `pxtran` (transpose) and `pxgemr2d` (layout transformation) functions. So, by using `cosma_pxgemm` you are implicitly also using our implementations of `pxtran` and `pxgemr2d`. We do this on purpose, as COSTA offers great speedups.

**Comment by yaoyi92** [comment] 2021-04-13 01:08
So, I end up using these commands to compile the test file. It seems the `-qopenmp` and `-lstdc++` are necessary here. Is this the correct way of doing the linking?

```
mpiifort -O3 -g -traceback -ip -fp-model precise -xCORE-AVX2 -qopenmp -c Scalapack.f90
mpiifort -qopenmp -lstdc++ Scalapack.o -L/nas/longleaf/home/yiy/softwares-dogwood/cosma/COSMA/install_2/lib64 -lcosma_pxgemm -lcosma -lcosta_scalapack -lcosta -L${MKLROOT}/lib/intel64 -lmkl_scalapack_lp64 -lmkl_blacs_intelmpi_lp64 -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_sequential -lmkl_core
```
The test file is

Scalapack.f90
```
program test
  call pdgemm
end program
```

**Comment by yaoyi92** [comment] 2021-04-13 01:15
Dear Marko,

However, if I tried this test file

Scalapack.f90
```
program test
  call pdgemr2d
end program
```
It gave me
```
/nas/longleaf/home/yiy/softwares-dogwood/cosma/COSMA/install_2/lib64/libcosta_scalapack.a(pxgemr2d.cpp.o): In function `pigemr2d':
pxgemr2d.cpp:(.text+0x4d): undefined reference to `void costa::pxgemr2d<int>(int, int, int const*, int, int, int const*, int*, int, int, int const*, int)'
/nas/longleaf/home/yiy/softwares-dogwood/cosma/COSMA/install_2/lib64/libcosta_scalapack.a(pxgemr2d.cpp.o): In function `pigemr2d_':
pxgemr2d.cpp:(.text+0x3ad): undefined reference to `void costa::pxgemr2d<int>(int, int, int const*, int, int, int const*, int*, int, int, int const*, int)'
/nas/longleaf/home/yiy/softwares-dogwood/cosma/COSMA/install_2/lib64/libcosta_scalapack.a(pxgemr2d.cpp.o): In function `pigemr2d__':
pxgemr2d.cpp:(.text+0x58d): undefined reference to `void costa::pxgemr2d<int>(int, int, int const*, int, int, int const*, int*, int, int, int const*, int)'
/nas/longleaf/home/yiy/softwares-dogwood/cosma/COSMA/install_2/lib64/libcosta_scalapack.a(pxgemr2d.cpp.o): In function `PIGEMR2D':
pxgemr2d.cpp:(.text+0x76d): undefined reference to `void costa::pxgemr2d<int>(int, int, int const*, int, int, int const*, int*, int, int, int const*, int)'
```
Am I missing anything?

**Comment by kabicm** [comment] 2021-04-13 01:41
Dear Yi, thanks for checking. This was caused by COSMA using an outdated version of COSTA. I have just updated the COSTA submodule in COSMA. Can you git clone recursively again the whole COSMA repo and try again? The latter should now be fixed.

**Comment by kabicm** [comment] 2021-04-13 01:46
Sorry, I would need some more time, I have to adapt few more things in COSMA to the latest COSTA version before it can work.

**Comment by yaoyi92** [comment] 2021-04-13 02:14
I see. No worry. Thank you for letting me know.

**Comment by kabicm** [comment] 2021-04-14 01:58
The latest commit should fix the issues with the latest version of COSTA. Since the COSTA library was also modified, it would be best to get a fresh new git clone of COSMA.

To answer your question regarding the OpenMP: you are right, we require it. However, most user codes already have OpenMP as a dependency (especially if they use a multithreaded versions of scalapack/lapack/blas). 

Let me know if this works for you and if you have any other issues!

**Comment by kabicm** [comment] 2021-04-16 18:55
Hi Yi (@yaoyi92), i just wanted to follow up on my previous comment: does it work for you now?

**Comment by yaoyi92** [comment] 2021-04-17 03:10
Yes, it works! Thank you so much!

**Comment by kabicm** [comment] 2021-04-22 08:49
Great, thanks for the feedback, I am glad it works now! The README will be improved soon, so I will now close this issue.

**Closed by kabicm** 2021-04-22 08:49 UTC
Labels: docs, enhancement
