### ISSUE TITLE
segfault for CP2K RPA

### ISSUE THREAD

**Issue by pseewald** [eth-cscs/COSMA#41] opened 2020-04-21 11:13 UTC
I get a segfault in COSMA for CP2K RPA on a system of 256 water molecules. The backtrace is:

```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#1  0x5529c30 in _ZN5cosma6Mapper5ownerERNS_10Interval2DE
    at /scratch/snx3000/pseewald/rpa_benchmarks_cosma/COSMA/src/cosma/mapper.cpp:362
#2  0x5529c30 in _ZN5cosma6Mapper15get_layout_gridEv
    at /scratch/snx3000/pseewald/rpa_benchmarks_cosma/COSMA/src/cosma/mapper.cpp:401
#3  0x550b504 in _ZN5cosma6pxgemmIdEEvcciiiT_PKS1_iiPKiS3_iiS5_S1_PS1_iiS5_
    at /scratch/snx3000/pseewald/rpa_benchmarks_cosma/COSMA/src/cosma/cosma_pxgemm.cpp:190
#4  0x246aad2 in __cp_fm_basic_linalg_MOD_cp_fm_gemm
    at /scratch/snx3000/pseewald/rpa_benchmarks_cosma/cp2k/src/fm/cp_fm_basic_linalg.F:449
#5  0xf27025 in __cp_gemm_interface_MOD_cp_gemm
    at /scratch/snx3000/pseewald/rpa_benchmarks_cosma/cp2k/src/cp_gemm_interface.F:136
#6  0x1d59ede in contract_s_to_q
    at /scratch/snx3000/pseewald/rpa_benchmarks_cosma/cp2k/src/rpa_util.F:810
```
The calculation was run on Piz Daint gpu partition / 1024 nodes with 12 OMP threads per rank.

CP2K input file:
[H2O-RI-RPA-TZ-COSMA.inp.txt](https://github.com/eth-cscs/COSMA/files/4509561/H2O-RI-RPA-TZ-COSMA.inp.txt)

I used COSMA commit 374ddb4ecdd8991a61527d9e538b515f5d42fb2e

**Comment by kabicm** [comment] 2020-04-21 11:26
Thanks @pseewald! Confirmed, reproduced, working on it now.

**Comment by kabicm** [comment] 2020-04-21 15:05
The bug is fixed in the commit 92965d07baa7e9f27e47134c2452f8e33535603f.

It was caused by int overflow operations. Now the full CP2K benchmark (256 RPA-RI for water molecules) is able to run on 1024 GPU nodes.

**Closed by kabicm** 2020-04-21 15:05 UTC
Labels: bug

**Comment by pseewald** [comment] 2020-04-21 15:11
Fantastic, thanks a lot!

**Comment by pseewald** [comment] 2020-04-21 19:05
Now I get a segfault when I try to run the same input on 256 nodes.

```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x2aaac43d11df in ???
#1  0x2aaac43d1160 in ???
#2  0x2aaac43d2740 in ???
#3  0x2aaab7478164 in _ZN9__gnu_cxx27__verbose_terminate_handlerEv
    at ../../../../cray-gcc-7.3.0-201811010911.14caf3e3fa4c2/libstdc++-v3/libsupc++/vterminate.cc:95
#4  0x2aaab7475f55 in _ZN10__cxxabiv111__terminateEPFvvE
    at ../../../../cray-gcc-7.3.0-201811010911.14caf3e3fa4c2/libstdc++-v3/libsupc++/eh_terminate.cc:47
#5  0x2aaab7475fa0 in _ZSt9terminatev
    at ../../../../cray-gcc-7.3.0-201811010911.14caf3e3fa4c2/libstdc++-v3/libsupc++/eh_terminate.cc:57
#6  0x2aaab74761e2 in __cxa_throw
    at ../../../../cray-gcc-7.3.0-201811010911.14caf3e3fa4c2/libstdc++-v3/libsupc++/eh_throw.cc:93
#7  0x2aaab7474ed1 in __cxa_throw_bad_array_new_length
    at ../../../../cray-gcc-7.3.0-201811010911.14caf3e3fa4c2/libstdc++-v3/libsupc++/eh_aux_runtime.cc:42
#8  0x5578d23 in _ZN9grid2grid18communication_dataIdEC2ERSt6vectorINS_7messageIdEESaIS4_EEii
    at /scratch/snx3000/pseewald/rpa_benchmarks_cosma/COSMA/libs/grid2grid/src/grid2grid/communication_data.cpp:86
#9  0x5571426 in _ZN9grid2grid15prepare_to_sendIdEENS_18communication_dataIT_EERSt6vectorISt17reference_wrapperINS_11grid_layoutIS2_EEESaIS8_EESB_i
    at /scratch/snx3000/pseewald/rpa_benchmarks_cosma/COSMA/libs/grid2grid/src/grid2grid/transform.cpp:172
#10  0x5571522 in _ZN9grid2grid9transformIdEEvRSt6vectorISt17reference_wrapperINS_11grid_layoutIT_EEESaIS6_EES9_i
    at /scratch/snx3000/pseewald/rpa_benchmarks_cosma/COSMA/libs/grid2grid/src/grid2grid/transform.cpp:655
#11  0x550bf05 in _ZN9grid2grid11transformerIdE9transformEv
    at /scratch/snx3000/pseewald/rpa_benchmarks_cosma/COSMA/libs/grid2grid/src/grid2grid/transformer.hpp:31
#12  0x550bf05 in _ZN5cosma6pxgemmIdEEvcciiiT_PKS1_iiPKiS3_iiS5_S1_PS1_iiS5_
    at /scratch/snx3000/pseewald/rpa_benchmarks_cosma/COSMA/src/cosma/cosma_pxgemm.cpp:313
#13  0x246aad2 in __cp_fm_basic_linalg_MOD_cp_fm_gemm
    at /scratch/snx3000/pseewald/rpa_benchmarks_cosma/cp2k/src/fm/cp_fm_basic_linalg.F:449
#14  0xf27025 in __cp_gemm_interface_MOD_cp_gemm
    at /scratch/snx3000/pseewald/rpa_benchmarks_cosma/cp2k/src/cp_gemm_interface.F:136
#15  0x1d59ede in contract_s_to_q
    at /scratch/snx3000/pseewald/rpa_benchmarks_cosma/cp2k/src/rpa_util.F:810
```

I set the environment variable
```
export COSMA_CPU_MAX_MEMORY=64000
```
to make the calculation fit on 256 nodes.

COSMA commit 92965d07baa7e9f27e47134c2452f8e33535603f
