### ISSUE TITLE
Subscript operator on empty vector

### ISSUE THREAD

**Issue by noma** [eth-cscs/COSMA#83] opened 2021-03-16 16:51 UTC
Stumbled across this:

https://github.com/eth-cscs/COSMA/blob/d0ab1dd8e53ae2301ff361504d1a80b6a88d303e/src/cosma/cosma_pxgemm.cpp#L276

should probably use `push_back()`, as the vector is default initialised in 250.

**Comment by kabicm** [comment] 2021-03-16 16:53
Thanks @noma, you are totally right. This was a recent change that was not present in the previous release, so it's a good catch!

**Comment by kabicm** [comment] 2021-03-16 16:55
Although it's still unclear why this wasn't caught by our CI tests, as we also run address sanitizer tests on each commit. We will have to investigate it.

**Comment by noma** [comment] 2021-03-16 17:00
I'd guess your tests didn't trigger 174 due to lack of a suitable input.

**Comment by kabicm** [comment] 2021-03-16 17:03
True, I just verified it and now I see what the problem is. Thanks again for catching this!

**Comment by kabicm** [comment] 2021-04-02 15:50
This should be fixed in: 35e2ddaeda9310e1bf27837240c93a9468575272. Thanks again for reporting this!

**Closed by kabicm** 2021-04-02 15:50 UTC
